FROM debian:trixie

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    gnat \
    groff \
    make \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /work

CMD ["/bin/sh"]
